import random

MEETINGS = [
    # Original favorites
    "Hops Review",
    "Stakeholder Aleignment",
    "Liquid Assets Review",
    "Pint-sized Planning",
    "Hopportunity Assessment",
    "The Pourfolio Review",
    "Yeast Mode Activation",
    "Brewdget Planning",
    "Quarterly Pint Review",
    "Fermentation Strategy Sync",
    "Malt Analysis",
    "Keg Performance Review",
    "Draft Proposal Meeting",
    "Stout Strategy Session",
    "Pilsner Pipeline Review",
    "Foam Forecast Meeting",
    "Cask Flow Analysis",
    "Tap-line Optimization",
    "IPA Impact Assessment",
    "Porter Progress Review",
    "Ale Hands",
    "Brewtrospective",
    "Mash Metrics Review",
    "Amber Alert Meeting",
    "Head Retention Meeting",
    "Bitterness Index Review",
    "Tankard Team Sync",
    "Brewsiness Review",
    "Maltinational Strategy",
    "Froth Forward Planning",
    "Last Orders Leadership Sync",
    "Tab Review Meeting",
    "On Tap This Quarter",
    "Publican Planning",
    "Cold One Kickoff",
    "Sipnificant Updates",
    "Pils and Skills Review",
    "Malty Discussion",
    "Fermenting Goals",
    "Half Pint Huddle",
    "Flagon Forecasting",
    "Draught Meeting",
    "Tapped In Team Talk",
    "Pour Decisions Review",
    "Alegorithm Review",
    "ABV Analysis",
    "Hops Analysis",
    # The second round. House rule: must survive a manager's glance.
    # Frameworks and formalities
    "Porter's Five Forces Analysis",
    "Gose-to-Market Strategy",
    "Objectives and Keg Results",
    "Key Pint Indicators Review",
    "Annual General Malting",
    "Minimum Viable Pint Workshop",
    "Tripel Bottom Line Review",
    "Target Operating Model Workshop",
    "Challenger Brand Positioning Review",
    "Corporate Tavernance Review",
    "Stoutcome Mapping Session",
    "Steinholder Engagement Review",
    "Single Pint of Contact Review",
    "Dubbel Booking Resolution",
    "Exact Change Management Workshop",
    # Finance and commercial
    "Bottoms-Up Budgeting",
    "Crown Cap Table Review",
    "Overdraught Protection Planning",
    "Petty Cask Reconciliation",
    "Sudsidiary Consolidation Review",
    "Unit Economics Deep Dive",
    "Minimum Unit Pricing Review",
    "Funding Round Close-Out",
    "Outstanding Chasers Review",
    "Closing Time Deal Review",
    "Double-Barrelled Growth Strategy",
    "Market Saisonality Analysis",
    "Spillover Effects Analysis",
    "Landlord Renegotiation Prep",
    # Engineering
    "Kanbrew Board Review",
    "Keglog Grooming Session",
    "Hoppy Path Testing Review",
    "Hand-Pull Request Review",
    "Pub-Sub Architecture Review",
    "On-Premise Migration Review",
    "Widget Redesign Workshop",
    "Keystone Dependency Review",
    "Cascade Deployment Review",
    "Bottleneck Throughput Review",
    "Trubleshooting Workshop",
    "Mild Severity Incident Review",
    "Prost-Mortem Review",
    "Watering Hole Threat Briefing",
    "Thirst-Party Integration Review",
    "Imperial Units Migration Planning",
    "Perry Programming Session",
    "Skunked Works Innovation Lab",
    "Wort in Progress Review",
    "Wort Case Scenario Planning",
    "Late Additions Scope Review",
    # Data and analytics
    "Customer Sediment Analysis",
    "Fruit Machine Learning Workshop",
    "Lagering Indicators Review",
    "Line-Cleaning Data Hygiene Audit",
    "Attenuation to Detail Audit",
    "Final Gravity Sign-Off",
    "Sherry-Picked Metrics Review",
    "Amber Status Deep Dive",
    "Golding Ratio Design Review",
    # Strategy and planning
    "One for the Roadmap",
    "Big Pitcher Thinking Session",
    "Caskading Goals Workshop",
    "Multicasking Workshop",
    "Untapped Potential Workshop",
    "Bright Tank Strategy Session",
    "Pale Imitation Competitor Analysis",
    "Flight Planning Workshop",
    "Storm Brewing Risk Register",
    "Pint of No Return Escalation",
    "After-Hours Vendor Lock-In Review",
    "Half-Measures Elimination Review",
    "Same-Again Recurring Sync",
    "Cider Effects Assessment",
    # People and culture
    "Culture Propagation Workshop",
    "Starter Culture Onboarding",
    "Oatstanding Achievement Awards",
    "Ale and Hearty Wellness Check",
    "Bottled-Up Feedback Session",
    "Brewtally Honest Feedback Exchange",
    "Structured Venting Session",
    "Bitter Lessons Debrief",
    "Lees Learned Retrospective",
    "Morning After-Action Review",
    "Bar-Raising Standards Workshop",
    "Taster Session Rollout",
    "Cask Me Anything",
    "Next Round Table Discussion",
    "Meading of the Minds",
    "Bock to Basics Workshop",
    # Comms and governance
    "PowerPint Presentation Review",
    "Carbonation Copy Briefing",
    "Crisp Messaging Workshop",
    "Final Proofing and Sign-Off",
    "Draught Exclusions Review",
    "Off-Licence Compliance Audit",
    "Spirit Level Alignment Check",
    "Pitch Rate Optimization",
    "Round Robin Allocation Review",
    "Cellar Performance Review",
    "Best Cellar List Review",
]


def get_random_meeting() -> dict:
    return {"meeting_name": random.choice(MEETINGS)}
