import random

MEETINGS = [
    # Original favorites
    "Hops Review",
    "Stakeholder Aleignment",
    "Liquid Assets Review",
    "Pint-sized Planning",
    "Hopportunity Assessment",
    "The Pourfolio Review",
    "Yeast Mode Activation",
    "Brewdget Planning",
    "Quarterly Pint Review",
    "Fermentation Strategy Sync",
    "Malt Analysis",
    "Keg Performance Review",
    "Draft Proposal Meeting",
    "Stout Strategy Session",
    "Pilsner Pipeline Review",
    "Foam Forecast Meeting",
    "Cask Flow Analysis",
    "Tap-line Optimization",
    "IPA Impact Assessment",
    "Porter Progress Review",
    "Ale Hands",
    "Brewtrospective",
    "Mash Metrics Review",
    "Amber Alert Meeting",
    "Head Retention Meeting",
    "Bitterness Index Review",
    "Tankard Team Sync",
    "Brewsiness Review",
    "Maltinational Strategy",
    "Froth Forward Planning",
    "Last Orders Leadership Sync",
    "Tab Review Meeting",
    "On Tap This Quarter",
    "Publican Planning",
    "Cold One Kickoff",
    "Sipnificant Updates",
    "Pils and Skills Review",
    "Malty Discussion",
    "Fermenting Goals",
    "Half Pint Huddle",
    "Flagon Forecasting",
    "Brew Crew Sync",
    "Draught Meeting",
    "Tapped In Team Talk",
    "Pour Decisions Review",
    "Alegorithm Review",
    "ABV Analysis",
    "Hops Analysis"
]


def get_random_meeting() -> dict:
    return {"meeting_name": random.choice(MEETINGS)}
